---
####        host_vars/R1.yml
hostname: R1

# Interfaces requiring EIGRP authentication
eigrp_auth_interfaces:
  - GigabitEthernet0/1
  - GigabitEthernet0/2

# Physical interfaces configuration
eigrp_interfaces:
  - interface: GigabitEthernet0/1
    description: "Link from R1 to R2"
    ip_address: 12.12.12.1
    prefix: 30
  
  - interface: GigabitEthernet0/2
    description: "Link from R1 to R3"
    ip_address: 13.13.13.1
    prefix: 30

  - interface: GigabitEthernet0/3
    description: "Link from R1 to SW1"
    ip_address: 192.168.1.1
    prefix: 24
  
# Networks to advertise in EIGRP
eigrp_advertised_interfaces:
  - network: 12.12.12.1
    wildcard: 0.0.0.0
  - network: 13.13.13.1
    wildcard: 0.0.0.0
  - network: 192.168.1.1
    wildcard: 0.0.0.0

eigrp_passive_interfaces:
  - interface: GigabitEthernet0/3 