---
####        host_vars/R3.yml
hostname: R3

# Interfaces requiring EIGRP authentication
eigrp_auth_interfaces:
  - GigabitEthernet0/1

# Physical interfaces configuration
eigrp_interfaces:
  - interface: GigabitEthernet0/1
    description: "Link from R3 to R1"
    ip_address: 13.13.13.2
    prefix: 30

  - interface: GigabitEthernet0/3
    description: "Link from R3 to SW3"
    ip_address: 192.168.3.1
    prefix: 24
  
# Networks to advertise in EIGRP
eigrp_advertised_interfaces:
  - network: 13.13.13.2
    wildcard: 0.0.0.3
  - network: 192.168.3.1
    wildcard: 0.0.0.255