---
####        host_vars/R3.yml
hostname: R3
router_id: 3.3.3.3

loopback1:
  - network: 192.169.3.1
    mask: 255.255.255.0

# Interfaces requiring OSPF authentication
ospf_auth_interfaces:
  - GigabitEthernet0/3

# Physical interfaces configuration
ospf_interfaces:
  - interface: GigabitEthernet0/3
    description: "Link from R3 to R1"
    ip_address: 13.13.13.2
    prefix: 30

# Networks to advertise in OSPF
ospf_advertised_interfaces:
  - network: 13.13.13.2
    wildcard: 0.0.0.0
    ospf_area: 0
  - network: 192.169.3.1
    wildcard: 0.0.0.0
    ospf_area: 0


