---
####        host_vars/R5.yml
hostname: R5
router_id: 5.5.5.5

# Interfaces requiring OSPF authentication
ospf_auth_interfaces:
  - GigabitEthernet0/5

# Physical interfaces configuration
ospf_interfaces:
  - interface: GigabitEthernet0/5
    description: "Link from R5 to R1"
    ip_address: 15.15.15.2
    prefix: 30
  
  - interface: Loopback0
    description: "For Router_id"
    ip_address: 5.5.5.5
    prefix: 32

  - interface: Loopback1
    description: "For internal network"
    ip_address: 192.169.5.1
    prefix: 24

# Networks to advertise in OSPF
ospf_advertised_interfaces:
  - network: 15.15.15.2
    wildcard: 0.0.0.0
    ospf_area: 10
  - network: 192.169.5.1
    wildcard: 0.0.0.0
    ospf_area: 10


